### ISSUE TITLE
Changes to FTP directory layout in Ensembl Genomes 43 / Ensembl 96

### ISSUE THREAD

**Issue by hxin** [sidbdri/sidbdri-utils#6]
come across [this](http://www.ensembl.info/2019/03/18/changes-to-ftp-directory-layout-in-ensembl-genomes-43-ensembl-96/), may not affect us but will check when release later in April. 

> Changes to FTP directory layout in Ensembl Genomes 43 / Ensembl 96
>
> 18TH MARCH 2019 BY ASTRID (OUTREACH)·0 COMMENTS
>
> We will make changes to the directory layouts of both the Ensembl Genomes FTP server (ftp://ftp.ensemblgenomes.org/pub/) and the Ensembl GRCh37 FTP server (ftp://ftp.ensemblorg.ebi.ac.uk/pub/grch37/) that may affect your pipelines. These changes will come into effect in Ensembl Genomes release 43/Ensembl release 96, which are scheduled for April 2019. Here are the details, so that you can plan any required updates to existing scripts and pipelines ahead of the releases.

**Comment by lweasel** [comment]
Good spot.
